INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'uyi-project', 'coding', CURRENT_DATE, 0);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'uyi-project', 'Learn java', CURRENT_DATE, 0);


INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'uyi-project', 'Google Cloud', CURRENT_DATE, 0);